# Generated by Django 5.1.4 on 2026-09-02 09:31

import django.db.models.deletion
import django.utils.timezone
import lms.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('opened_on', models.DateField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('licence_number', models.CharField(blank=True, default='', max_length=100)),
                ('licence_expiry', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=200)),
                ('logo_initials', models.CharField(blank=True, default='', max_length=3)),
                ('brand_color', models.CharField(default='#EE0033', max_length=7)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('language', models.CharField(default='sw', max_length=2)),
                ('plan_level', models.CharField(default='starter', max_length=20)),
                ('staff_limit', models.IntegerField(default=10)),
                ('active_loan_limit', models.IntegerField(default=500)),
                ('sms_balance', models.IntegerField(default=0)),
                ('sms_sender_name', models.CharField(blank=True, default='', max_length=11)),
                ('sms_sender_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('role', models.CharField(choices=[('platform_admin', 'Platform Admin'), ('lender_admin', 'Lender Admin'), ('branch_manager', 'Branch Manager'), ('loan_officer', 'Loan Officer'), ('credit_committee', 'Credit Committee'), ('cashier', 'Cashier'), ('auditor', 'Auditor')], max_length=30)),
                ('approval_limit', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lms.branch')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='lms.lender')),
            ],
            options={
                'verbose_name_plural': 'staff',
                'ordering': ['name'],
            },
            managers=[
                ('objects', lms.managers.StaffManager()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('term_instalments', models.IntegerField()),
                ('purpose', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('declined', 'Declined'), ('disbursed', 'Disbursed')], default='pending_approval', max_length=20)),
                ('declared_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('declared_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('affordability_pass', models.BooleanField(default=True)),
                ('duplicate_check_pass', models.BooleanField(default=True)),
                ('blacklist_check_pass', models.BooleanField(default=True)),
                ('credit_bureau_consent', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('score_recommendation', models.CharField(blank=True, choices=[('recommend', 'Recommend'), ('caution', 'Caution'), ('decline', 'Decline')], max_length=20, null=True)),
                ('required_approver_role', models.CharField(choices=[('platform_admin', 'Platform Admin'), ('lender_admin', 'Lender Admin'), ('branch_manager', 'Branch Manager'), ('loan_officer', 'Loan Officer'), ('credit_committee', 'Credit Committee'), ('cashier', 'Cashier'), ('auditor', 'Auditor')], max_length=30)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approver_name', models.CharField(blank=True, default='', max_length=150)),
                ('role', models.CharField(choices=[('platform_admin', 'Platform Admin'), ('lender_admin', 'Lender Admin'), ('branch_manager', 'Branch Manager'), ('loan_officer', 'Loan Officer'), ('credit_committee', 'Credit Committee'), ('cashier', 'Cashier'), ('auditor', 'Auditor')], max_length=30)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined')], max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, default='')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='lms.application')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=150, null=True)),
                ('years_trading', models.IntegerField(blank=True, null=True)),
                ('national_id', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('residence', models.CharField(blank=True, default='', max_length=250)),
                ('occupation', models.CharField(blank=True, default='', max_length=150)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('next_of_kin', models.CharField(blank=True, default='', max_length=200)),
                ('blacklisted', models.BooleanField(default=False)),
                ('blacklist_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lms.branch')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowers', to='lms.lender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='lms.borrower'),
        ),
        migrations.CreateModel(
            name='BorrowerDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lms.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerHistoryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('label', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True, default='')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='lms.borrower')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lms.branch'),
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('national_id', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_date', models.DateField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='lms.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=150)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='lms.lender')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='lms.lender'),
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.CharField(max_length=36)),
                ('user_name', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=50)),
                ('entity', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=36)),
                ('details', models.TextField(blank=True, default='')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='lms.lender')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='lms.lender'),
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('interest_method', models.CharField(choices=[('reducing', 'Reducing'), ('flat', 'Flat')], max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('interest_period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('repayment_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly')], max_length=20)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('min_term_instalments', models.IntegerField()),
                ('max_term_instalments', models.IntegerField()),
                ('step_up_enabled', models.BooleanField(default=False)),
                ('grace_period_days', models.IntegerField(default=0)),
                ('grace_period_applies_to', models.CharField(choices=[('principal', 'Principal'), ('interest', 'Interest'), ('both', 'Both'), ('none', 'None')], default='none', max_length=20)),
                ('penalty_kind', models.CharField(max_length=10)),
                ('penalty_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('penalty_cap', models.DecimalField(decimal_places=2, max_digits=14)),
                ('allocation_order', models.JSONField(default=list)),
                ('security_required', models.JSONField(default=list)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='lms.lender')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_disbursed', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fees_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending_disbursement', 'Pending Disbursement'), ('active', 'Active'), ('closed', 'Closed'), ('written_off', 'Written Off')], default='active', max_length=25)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('disbursement_channel', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('supplier', 'Supplier'), ('cash', 'Cash')], max_length=20)),
                ('disbursement_date', models.DateTimeField()),
                ('disbursement_reference', models.CharField(max_length=100)),
                ('disbursement_approved_by', models.CharField(max_length=150)),
                ('disbursement_disbursed_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='lms.application')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='lms.borrower')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lms.branch')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='lms.lender')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lms.loanproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('required_role', models.CharField(choices=[('platform_admin', 'Platform Admin'), ('lender_admin', 'Lender Admin'), ('branch_manager', 'Branch Manager'), ('loan_officer', 'Loan Officer'), ('credit_committee', 'Credit Committee'), ('cashier', 'Cashier'), ('auditor', 'Auditor')], max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_levels', to='lms.loanproduct')),
            ],
            options={
                'ordering': ['min_amount'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lms.loanproduct'),
        ),
        migrations.CreateModel(
            name='ProductFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timing', models.CharField(choices=[('deducted', 'Deducted'), ('added', 'Added')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='lms.loanproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank', 'Bank'), ('cash', 'Cash'), ('field', 'Field')], max_length=20)),
                ('receipt_number', models.CharField(db_index=True, max_length=30)),
                ('allocation_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('allocation_fees', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('allocation_interest', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('allocation_principal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('recorded_by', models.CharField(max_length=150)),
                ('reversed', models.BooleanField(default=False)),
                ('reversal_reason', models.TextField(blank=True, null=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='lms.lender')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='lms.loan')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleInstalment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.IntegerField()),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fees_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('penalty_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('due', 'Due'), ('overdue', 'Overdue'), ('paid', 'Paid'), ('partial', 'Partial')], default='upcoming', max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='lms.loan')),
            ],
            options={
                'ordering': ['period'],
            },
        ),
    ]
