# Generated by manage.py makemigrations (additive for an already-migrated DB)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='allocation_remainder',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
