# Generated by Django 5.1.4 on 2026-09-08 05:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_repayment_allocation_remainder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('call', 'Call'), ('visit', 'Visit'), ('message', 'Message'), ('note', 'Note'), ('promise', 'Promise')], max_length=12)),
                ('outcome', models.CharField(blank=True, choices=[('reached', 'Reached'), ('no_answer', 'No Answer'), ('promised', 'Promised'), ('disputed', 'Disputed'), ('paid', 'Paid'), ('other', 'Other')], default='', max_length=12)),
                ('note', models.TextField(blank=True, default='')),
                ('promised_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('promised_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lms.borrower')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_activities', to='lms.lender')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_activities', to='lms.loan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
