# Generated by Django 5.1.4 on 2026-09-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_collectionactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='restructure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='restructured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='schedule_principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
