# Generated by Django 5.1.4 on 2026-09-08 06:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_loan_restructure_count_loan_restructured_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TillReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cashier_name', models.CharField(max_length=150)),
                ('business_date', models.DateField()),
                ('opening_float', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_close', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('counted_close', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lms.branch')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='till_reconciliations', to='lms.lender')),
            ],
            options={
                'ordering': ['-business_date', '-created_at'],
            },
        ),
    ]
