# Generated by Django 5.1.4 on 2026-09-08 06:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_loan_savings_deducted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('meeting_day', models.CharField(blank=True, default='', max_length=12)),
                ('meeting_frequency', models.CharField(blank=True, default='weekly', max_length=12)),
                ('formed_on', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lms.branch')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='lms.lender')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lms.borrowergroup'),
        ),
        migrations.AddField(
            model_name='loan',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='lms.borrowergroup'),
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('chair', 'Chair'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer')], default='member', max_length=12)),
                ('joined_on', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_memberships', to='lms.borrower')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='lms.borrowergroup')),
            ],
            options={
                'ordering': ['role', 'joined_on'],
                'unique_together': {('group', 'borrower')},
            },
        ),
    ]
