# Generated by Django 5.1.4 on 2026-09-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_borrowergroup_application_group_loan_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='session_timeout_minutes',
            field=models.IntegerField(default=20),
        ),
    ]
