# Generated by Django 5.1.4 on 2026-10-02 13:08

from django.db import migrations, models


def backfill(apps, schema_editor):
    Borrower = apps.get_model("lms", "Borrower")
    counters = {}
    for b in Borrower.objects.order_by("created_at"):
        n = counters.get(b.lender_id, 0) + 1
        counters[b.lender_id] = n
        b.customer_number = b.customer_number or f"CUS-{n:05d}"
        if b.blacklisted:
            b.status = "blacklisted"
        b.emergency_name = b.emergency_name or b.next_of_kin
        b.save(update_fields=["customer_number", "status", "emergency_name"])



class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_lender_session_timeout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='alt_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='borrower',
            name='bank_account',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='borrower',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='borrower',
            name='business_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='borrower',
            name='customer_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='borrower',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='borrower',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='borrower',
            name='emergency_address',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='borrower',
            name='emergency_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='borrower',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='borrower',
            name='emergency_relationship',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='borrower',
            name='employer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='borrower',
            name='employment_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='borrower',
            name='existing_loan_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='borrower',
            name='existing_loans',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='borrower',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='borrower',
            name='income_source',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='borrower',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='borrower',
            name='marital_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='borrower',
            name='mobile_money_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='borrower',
            name='mobile_money_provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='borrower',
            name='monthly_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='borrower',
            name='other_income_sources',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='borrower',
            name='postal_address',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='borrower',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='borrower',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('blacklisted', 'Blacklisted')], default='active', max_length=12),
        ),
        migrations.AddField(
            model_name='borrower',
            name='street',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='borrower',
            name='ward',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='borrower',
            name='years_employed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='address',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='guarantee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='relationship',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='status',
            field=models.CharField(default='pending', max_length=12),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
