# Generated by Django 5.1.4 on 2026-10-02 13:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_borrower_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='risk',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='changes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='borrower',
            name='dependents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrower',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrower',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='verified_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='scheduleinstalment',
            name='was_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collectionactivity',
            name='kind',
            field=models.CharField(choices=[('call', 'Call'), ('visit', 'Visit'), ('message', 'Message'), ('note', 'Note'), ('promise', 'Promise'), ('escalation', 'Escalation')], max_length=12),
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=250)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('owner_name', models.CharField(blank=True, default='', max_length=200)),
                ('ownership_document', models.CharField(blank=True, default='', max_length=200)),
                ('valuation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pledged', 'Pledged'), ('active', 'Active'), ('released', 'Released'), ('seized', 'Seized')], default='pledged', max_length=10)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collateral', to='lms.borrower')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collateral', to='lms.lender')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collateral', to='lms.loan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
