# Generated by Django 5.1.4 on 2026-10-02 13:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_verification_collateral_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='batch',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='segments',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_by',
            field=models.CharField(blank=True, default='System', max_length=150),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=30)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('network', models.CharField(max_length=20)),
                ('provider', models.CharField(max_length=30)),
                ('provider_ref', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=250)),
                ('receipt', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lms.application')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lms.borrower')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='lms.lender')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lms.loan')),
                ('repayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lms.repayment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
