# Generated by Django 5.1.4 on 2026-10-02 14:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def backfill(apps, schema_editor):
    Group = apps.get_model("lms", "BorrowerGroup")
    Membership = apps.get_model("lms", "GroupMembership")
    counters = {}
    for g in Group.objects.order_by("created_at"):
        n = counters.get(g.lender_id, 0) + 1
        counters[g.lender_id] = n
        g.group_number = g.group_number or f"GRP-{n:04d}"
        g.status = "active" if g.active else "suspended"
        g.save(update_fields=["group_number", "status"])
        for i, m in enumerate(Membership.objects.filter(group=g).order_by("joined_on", "id"), start=1):
            m.membership_number = m.membership_number or f"{g.group_number}-{i:02d}"
            m.status = "active" if m.active else "left"
            m.save(update_fields=["membership_number", "status"])



class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_sms_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowergroup',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='borrowergroup',
            name='group_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='borrowergroup',
            name='group_type',
            field=models.CharField(blank=True, default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='borrowergroup',
            name='loan_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='borrowergroup',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='borrowergroup',
            name='meeting_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='borrowergroup',
            name='meeting_time',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='borrowergroup',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='borrowergroup',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='borrowergroup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='borrowergroup',
            name='ward',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='left_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='membership_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('left', 'Left')], default='active', max_length=10),
        ),
        migrations.CreateModel(
            name='GroupDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lms.borrowergroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupHistoryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('label', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True, default='')),
                ('by', models.CharField(blank=True, default='', max_length=150)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='lms.borrowergroup')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GroupMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('collection_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('recorded_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='lms.borrowergroup')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('present', models.BooleanField(default=True)),
                ('contribution', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lms.groupmembership')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='lms.groupmeeting')),
            ],
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
