# Generated by Django 5.1.4 on 2026-10-02 20:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Existing applications predate the staged workflow: keep their requested
    terms, and treat anything already past intake as assessed by its creator."""
    Application = apps.get_model("lms", "Application")
    ApplicationEvent = apps.get_model("lms", "ApplicationEvent")
    Staff = apps.get_model("lms", "Staff")
    names = dict(Staff.objects.values_list("id", "name"))
    results = {"recommend": "recommended", "caution": "further_review", "decline": "not_recommended"}
    for a in Application.objects.all():
        a.requested_amount = a.amount
        a.requested_term = a.term_instalments
        a.loan_officer_id = a.created_by_id
        a.application_date = a.created_at.date()
        by = names.get(a.created_by_id, "")
        ApplicationEvent.objects.create(application=a, stage="submitted", label="Application submitted", by=by, at=a.created_at)
        if a.status in ("pending_approval", "approved", "declined", "disbursed"):
            a.assessment_result = results.get(a.score_recommendation or "", "recommended")
            a.assessed_amount = a.amount
            a.recommended_term = a.term_instalments
            a.assessed_by_id = a.created_by_id
            a.assessed_at = a.created_at
            a.assessment_notes = "Recorded before the staged approval workflow."
            ApplicationEvent.objects.create(application=a, stage="pending_approval", label="Assessed and forwarded for approval",
                                            by=by, at=a.created_at)
        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_group_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='application',
            name='assessed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='assessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='assessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='assessment_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='assessment_result',
            field=models.CharField(blank=True, choices=[('recommended', 'Recommended'), ('further_review', 'Further Review'), ('not_recommended', 'Not Recommended')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='business_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='application',
            name='business_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='application',
            name='collateral',
            field=models.ManyToManyField(blank=True, related_name='applications', to='lms.collateral'),
        ),
        migrations.AddField(
            model_name='application',
            name='dependents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='disbursement_method',
            field=models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('supplier', 'Supplier'), ('cash', 'Cash')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='existing_loans_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='existing_repayments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='application',
            name='first_repayment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='group_members',
            field=models.ManyToManyField(blank=True, related_name='+', to='lms.borrower'),
        ),
        migrations.AddField(
            model_name='application',
            name='guarantors',
            field=models.ManyToManyField(blank=True, related_name='applications', to='lms.guarantor'),
        ),
        migrations.AddField(
            model_name='application',
            name='loan_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='other_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='application',
            name='recommended_term',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='application',
            name='requested_term',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collateral',
            name='documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='collateral',
            name='existing_claims',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='collateral',
            name='valued_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_assessment', 'Under Assessment'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('declined', 'Declined'), ('disbursed', 'Disbursed')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='approvaldecision',
            name='decision',
            field=models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined'), ('returned', 'Returned')], max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=250)),
                ('verified_by', models.CharField(blank=True, default='', max_length=150)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=150)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lms.application')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_assessment', 'Under Assessment'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('declined', 'Declined'), ('disbursed', 'Disbursed')], max_length=20)),
                ('label', models.CharField(max_length=150)),
                ('note', models.TextField(blank=True, default='')),
                ('by', models.CharField(blank=True, default='', max_length=150)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='lms.application')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
