# Generated by Django 5.1.4 on 2026-10-02 21:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


from decimal import Decimal

CHANNEL_ACCOUNT = {"mobile_money": "mobile_money", "bank_transfer": "bank", "bank": "bank", "supplier": "bank",
                   "cash": "cash", "field": "cash", "wallet": "savings_deposits"}


def backfill(apps, schema_editor):
    """Loans that predate the controlled workflow: give them a loan number, a
    successful disbursement record and the ledger postings they would have made."""
    Lender = apps.get_model("lms", "Lender")
    Loan = apps.get_model("lms", "Loan")
    Repayment = apps.get_model("lms", "Repayment")
    Staff = apps.get_model("lms", "Staff")
    Disbursement = apps.get_model("lms", "Disbursement")
    DisbursementEvent = apps.get_model("lms", "DisbursementEvent")
    LedgerEntry = apps.get_model("lms", "LedgerEntry")
    D = lambda v: Decimal(str(round(float(v or 0), 2)))

    for lender in Lender.objects.all():
        journal = [0]
        staff_by_name = {s.name: s for s in Staff.objects.filter(lender=lender)}

        def post(lines, when, description, reference="", by="", loan=None, disbursement=None, repayment=None):
            rows = [(a, D(dr), D(cr)) for a, dr, cr in lines if D(dr) or D(cr)]
            if not rows:
                return
            journal[0] += 1
            for a, dr, cr in rows:
                LedgerEntry.objects.create(
                    lender=lender, journal=f"JNL-{journal[0]:06d}", date=when, account=a, debit=dr, credit=cr,
                    description=description, reference=reference, created_by=by, loan=loan,
                    disbursement=disbursement, repayment=repayment,
                )

        for n, loan in enumerate(Loan.objects.filter(lender=lender).select_related("application", "borrower").order_by("created_at"), 1):
            loan.loan_number = f"LN-{n:06d}"
            loan.save(update_fields=["loan_number"])
            app = loan.application
            processor = staff_by_name.get(loan.disbursement_disbursed_by) or app.created_by
            principal, fees, savings = D(loan.principal), D(loan.fees_deducted), D(loan.savings_deducted)
            d = Disbursement.objects.create(
                lender=lender, number=f"DIS-{n:06d}", application=app, loan=loan, status="successful",
                approved_amount=principal, fees=[{"name": "Fees deducted", "amount": float(fees)}] if fees else [],
                fees_total=fees, savings_deducted=savings, net_amount=principal - fees - savings,
                method=loan.disbursement_channel, recipient_name=loan.borrower.full_name,
                recipient_account=loan.borrower.phone, destination_verified=True,
                prepared_by=processor, prepared_at=loan.disbursement_date, processed_by=processor,
                processed_at=loan.disbursement_date, confirmed_at=loan.disbursement_date,
                transaction_reference=loan.disbursement_reference, created_at=loan.disbursement_date,
            )
            DisbursementEvent.objects.create(
                disbursement=d, status="successful", by=loan.disbursement_disbursed_by, at=loan.disbursement_date,
                action="Recorded before the controlled disbursement workflow",
                note=f"Approved by {loan.disbursement_approved_by}, released by {loan.disbursement_disbursed_by}",
            )
            post([("loan_portfolio", principal, 0), (CHANNEL_ACCOUNT.get(loan.disbursement_channel, "bank"), 0, principal - fees - savings),
                  ("fee_income", 0, fees), ("savings_deposits", 0, savings)],
                 loan.disbursement_date, f"Loan {loan.loan_number} disbursed ({d.number})", loan.disbursement_reference,
                 loan.disbursement_disbursed_by, loan=loan, disbursement=d)

            principal_out = principal
            for r in Repayment.objects.filter(loan=loan).order_by("date"):
                lines = [(CHANNEL_ACCOUNT.get(r.channel, "cash"), r.amount, 0), ("loan_portfolio", 0, r.allocation_principal),
                         ("interest_income", 0, r.allocation_interest), ("fee_income", 0, r.allocation_fees),
                         ("penalty_income", 0, r.allocation_penalty),
                         ("suspense", 0, D(r.amount) - D(r.allocation_principal) - D(r.allocation_interest)
                          - D(r.allocation_fees) - D(r.allocation_penalty))]
                post(lines, r.date, f"Repayment {r.receipt_number} on loan {loan.loan_number}", r.receipt_number,
                     r.recorded_by, loan=loan, repayment=r)
                principal_out -= D(r.allocation_principal)
                if r.reversed:
                    post([(a, cr, dr) for a, dr, cr in lines], r.date, f"Reversal of repayment {r.receipt_number}",
                         r.receipt_number, r.recorded_by, loan=loan, repayment=r)
                    principal_out += D(r.allocation_principal)
            if loan.status == "written_off" and principal_out > 0:
                post([("write_off_expense", principal_out, 0), ("loan_portfolio", 0, principal_out)],
                     loan.closed_at or loan.disbursement_date, f"Loan {loan.loan_number} written off", loan=loan)


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_application_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='dual_authorisation_threshold',
            field=models.DecimalField(decimal_places=2, default=5000000, max_digits=14),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='disbursement_method',
            field=models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('supplier', 'Supplier'), ('cash', 'Cash'), ('wallet', 'Wallet')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='disbursement_channel',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('supplier', 'Supplier'), ('cash', 'Cash'), ('wallet', 'Wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending_disbursement', 'Pending Disbursement'), ('active', 'Active'), ('closed', 'Closed'), ('written_off', 'Written Off'), ('reversed', 'Reversed')], default='active', max_length=25),
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_verification', 'Under Verification'), ('approved', 'Approved'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fees', models.JSONField(blank=True, default=list)),
                ('fees_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('savings_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_deductions', models.JSONField(blank=True, default=list)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('supplier', 'Supplier'), ('cash', 'Cash'), ('wallet', 'Wallet')], max_length=20)),
                ('recipient_type', models.CharField(default='borrower', max_length=12)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=200)),
                ('recipient_provider', models.CharField(blank=True, default='', max_length=100)),
                ('recipient_account', models.CharField(blank=True, default='', max_length=100)),
                ('authorisation_note', models.CharField(blank=True, default='', max_length=250)),
                ('destination_verified', models.BooleanField(default=False)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('requires_dual_authorisation', models.BooleanField(default=False)),
                ('checks', models.JSONField(blank=True, default=dict)),
                ('override_reason', models.CharField(blank=True, default='', max_length=250)),
                ('prepared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('authorised_at', models.DateTimeField(blank=True, null=True)),
                ('second_authorised_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, default='', max_length=100)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=250)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=250)),
                ('reversal_reason', models.CharField(blank=True, default='', max_length=250)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='disbursements', to='lms.application')),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='lms.lender')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements', to='lms.loan')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lms.paymenttransaction')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('second_authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisbursementEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_verification', 'Under Verification'), ('approved', 'Approved'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], max_length=20)),
                ('action', models.CharField(max_length=150)),
                ('note', models.TextField(blank=True, default='')),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('by', models.CharField(blank=True, default='', max_length=150)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='lms.disbursement')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journal', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.CharField(db_index=True, max_length=30)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('description', models.CharField(max_length=250)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disbursement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ledger_entries', to='lms.disbursement')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='lms.lender')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ledger_entries', to='lms.loan')),
                ('repayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ledger_entries', to='lms.repayment')),
            ],
            options={
                'ordering': ['date', 'journal'],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
