# Generated by Django 5.1.4 on 2026-10-02 21:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Fill the new fields for repayments recorded before them."""
    Repayment = apps.get_model("lms", "Repayment")
    Loan = apps.get_model("lms", "Loan")
    Staff = apps.get_model("lms", "Staff")
    PaymentTransaction = apps.get_model("lms", "PaymentTransaction")
    names = {}
    for st in Staff.objects.all():
        names.setdefault((st.lender_id, st.name), st.pk)
    gateway = dict(PaymentTransaction.objects.filter(repayment__isnull=False, status="success")
                   .values_list("repayment_id", "receipt"))
    for loan in Loan.objects.prefetch_related("schedule"):
        payable = sum(float(i.total_due) for i in loan.schedule.all())
        paid = 0.0
        for r in Repayment.objects.filter(loan=loan).order_by("date"):
            r.payment_date = r.date.date()
            r.branch_id = loan.branch_id
            r.received_by_id = names.get((r.lender_id, r.recorded_by))
            if not r.reversed:
                paid += float(r.amount)
            r.balance_after = round(max(payable - paid, 0), 2)
            if r.pk in gateway:
                r.reference = gateway[r.pk] or ""
                r.reconciliation_status = "reconciled"
                r.reconciled_at = r.date
                r.reconciled_by = "Payment gateway"
                r.reconciliation_note = "Confirmed by the payment gateway"
            r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_disbursement_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lms.branch'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='collection_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments', to='lms.collectionactivity'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='collection_point',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='repayment',
            name='corrects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='lms.repayment'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='repayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='repayment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repayment',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='reconciled_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='repayment',
            name='reconciliation_note',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='repayment',
            name='reconciliation_status',
            field=models.CharField(default='unreconciled', max_length=12),
        ),
        migrations.AddField(
            model_name='repayment',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='repayment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='reversed_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='channel',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank', 'Bank'), ('cash', 'Cash'), ('field', 'Field'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='GroupPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('channel', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank', 'Bank'), ('cash', 'Cash'), ('field', 'Field'), ('other', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('collection_point', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lms.borrowergroup')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_payments', to='lms.lender')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='repayment',
            name='group_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments', to='lms.grouppayment'),
        ),
        migrations.CreateModel(
            name='StatementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('batch', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('ignored', 'Ignored')], default='unmatched', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=250)),
                ('imported_by', models.CharField(max_length=150)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_line', to='lms.grouppayment')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_lines', to='lms.lender')),
                ('repayment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_line', to='lms.repayment')),
            ],
            options={
                'ordering': ['-date', '-imported_at'],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
