# Generated by Django 5.1.4 on 2026-10-03 06:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_repayment_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionactivity',
            name='amount_collected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='collectionactivity',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='collectionactivity',
            name='location',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='collectionactivity',
            name='next_action',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='collectionactivity',
            name='next_follow_up',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionactivity',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='collectionactivity',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='collectionactivity',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionactivity',
            name='visit_status',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='lender',
            name='collection_stages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='CollectionCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(default='pending_follow_up', max_length=24)),
                ('stage', models.CharField(default='overdue', max_length=40)),
                ('assigned_by', models.CharField(blank=True, default='', max_length=150)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, default='', max_length=250)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, default='', max_length=250)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_cases', to='lms.lender')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_cases', to='lms.loan')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='collectionactivity',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='lms.collectioncase'),
        ),
        migrations.CreateModel(
            name='CollectionCaseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=250)),
                ('note', models.TextField(blank=True, default='')),
                ('by', models.CharField(blank=True, default='', max_length=150)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='lms.collectioncase')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
    ]
