# Generated by Django 5.1.4 on 2026-10-03 06:27

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Existing products: status follows the old active flag; each approval tier's single role
    becomes its role list; applications get the approvals their tier requires."""
    LoanProduct = apps.get_model("lms", "LoanProduct")
    ApprovalLevel = apps.get_model("lms", "ApprovalLevel")
    Application = apps.get_model("lms", "Application")
    LoanProduct.objects.filter(active=False).update(status="inactive")
    for level in ApprovalLevel.objects.all():
        level.required_roles = [level.required_role]
        level.save(update_fields=["required_roles"])
    for app in Application.objects.all():
        app.required_approvals = [app.required_approver_role]
        app.save(update_fields=["required_approvals"])


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_collection_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='eligibility',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='required_approvals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='approvallevel',
            name='required_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='category',
            field=models.CharField(default='business', max_length=20),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='default_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='default_term',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='disbursement_methods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='early_repayment_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='first_repayment_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='first_repayment_rule',
            field=models.CharField(default='one_period', max_length=16),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='loan_type',
            field=models.CharField(default='individual', max_length=12),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='max_active_loans',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='max_disbursement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='max_group_exposure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='max_increase_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='max_open_applications',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='max_total_outstanding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='min_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='min_collateral_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='min_group_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='min_guarantors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='min_membership_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='min_monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='min_savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='penalty_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='penalty_grace_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='required_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='productfee',
            name='fee_type',
            field=models.CharField(default='other', max_length=20),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
