# Generated by Django 5.1.4 on 2026-10-03 07:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_product_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='mobile_money_account_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lender',
            name='mobile_money_network',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='lender',
            name='mobile_money_number',
            field=models.CharField(blank=True, default='0618750312', max_length=30),
        ),
        migrations.CreateModel(
            name='PortalAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_account', to='lms.borrowergroup')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_accounts', to='lms.lender')),
            ],
        ),
    ]
